---
title: "CaseStudy2"
author: "Kari Theobald, Shane Weinstock, Jeremey Simpson, Gabe Gonzales"
date: "4/3/2019"
output:
  html_document:
    keep_md: yes
---
```{r, echo=TRUE, cache=TRUE}
sessionInfo()
```

```{r, echo=TRUE, cache=TRUE, include = TRUE}
install.packages("readxl")
install.packages("ggplot2")

library(readxl)
setwd("~/Desktop/Kari/SMU /Doing Data Science/Homework/CaseStudy2/CaseStudy2")
New.Data <- read_xlsx("~/Desktop/Kari/SMU /Doing Data Science/Homework/CaseStudy2/CaseStudy2/CaseStudy2-data.xlsx")
Data <- data.frame(New.Data)
head(Data) # original import of all data 
dim(Data) # how many rows and columns in the original data set. 

Data
#Change col names to less than 12 characters in the  dataframe. 
names <- c( "Age", "Attrition", "Feq.Travel", "Daily.Rate", "Department", "mlg.Home", "Education", "Ed.Field", "Emp.Count", "Emp.Number", "Env.Sat", "Gender", "HourlyRate", "Job.Invol", "Job.Level", "Title", "Satisfied", "M.S.D", "Income.mos","Rate.mos", "Jobs.Worked", "Over18", "OT", "Percent.Inc" , "Performance", "Sat.Relation", "Hours", "Stock", "Yrs.Wrkd", "Training", "Work.Life", "YOS", "YCRole","YbtwnPromo", "YwMgmt")

Data <- setNames(Data, names)

Data  #check new names
summary(Data)

#Anyone under 18?
Over18 <- grep("N", Small.Data$Over18)
Over18

#Reduce the col in the dataframe.
Small.Data <- data.frame(Data$Attrition, Data$Age, Data$Gender, Data$M.S.D, Data$YOS,   Data$Ed.Field, Data$Title, Data$Rate.mos, Data$mlg.Home)      

#Change col names in the smaller dataframe. 
names <- c( "Attrition", "Age", "Gender", "M.S.D", "YOS", "Education", "Title", "Income.mos", "mlg.Home")
Small.Data <- setNames (Small.Data, names)
head(Small.Data)

summary(Small.Data)

#Is anyone under 18 participating in the study?
Over18 <- grep("N", Small.Data$Over18)
Over18
# repsonse is 0. So all are considered over 18 by their response. There are 8 people who state they are 18 but we understand this response to be 18, plus a few days or months. Therefore we are leaving them in the study. 



plot(Small.Data$Gender)
plot(Small.Data$Attrition)


summary(Small.Data$Monthly.Income)

### don't use this below.. this charge totals all the monthly income per category. We need to average the income and then plot.
library(ggplot2)
par(las=2)
Jobs<-ggplot(data=Small.Data, aes(x=Title, y=Income.mos, fill=Title))  + geom_bar(stat="identity") + xlab("Titles") +  ylab("Monthly Income") + ggtitle("Jobs that Pay") + theme(plot.title = element_text(hjust = 0.5))+ coord_flip()
Jobs
```

```{r, echo=TRUE, cache=TRUE, include=TRUE}
#Using only the data where Attrition is True. 

setwd("~/Desktop/Kari/SMU /Doing Data Science/Homework/CaseStudy2/CaseStudy2")

New.Data <- read_xlsx("~/Desktop/Kari/SMU /Doing Data Science/Homework/CaseStudy2/CaseStudy2/CaseStudy2-data.xlsx")

Data <- data.frame(New.Data)

names <- c( "Age", "Attrition", "Feq.Travel", "Daily.Rate", "Department", "mlg.Home", "Education", "Ed.Field", "Emp.Count", "Emp.Number", "Env.Sat", "Gender", "HourlyRate", "Job.Invol", "Job.Level", "Title", "Satisfied", "M.S.D", "Income.mos","Rate.mos", "Jobs.Worked", "Over18", "OT", "Percent.Inc" , "Performance", "Sat.Relation", "Hours", "Stock", "Yrs.Wrkd", "Training", "Work.Life", "YOS", "YCRole","YbtwnPromo", "YwMgmt")

Data <- setNames(Data, names)

Small.Data <- data.frame(Data$Attrition, Data$Age, Data$Gender, Data$M.S.D, Data$YOS,   Data$Ed.Field, Data$Title, Data$Rate.mos, Data$mlg.Home)      

#Change col names in the smaller dataframe. 
names <- c( "Attrition", "Age", "Gender", "M.S.D", "YOS", "Education", "Title", "Income.mos", "mlg.Home")
Small.Data <- setNames (Small.Data, names)

library(plyr)
Small.Data$Attrition <- revalue(Small.Data$Attrition, c("Yes"=1, "No" = 0))
Small.Data$Attrition
True.Attrition<- subset(Small.Data, Small.Data$Attrition==1)
True.Attrition
summary(True.Attrition)

hist(True.Attrition$mlg.Home, 
     main="Miles from Home Impacting Attrition", 
     xlab="Miles from Home",
     ylab="Number of People ", 
     border="blue", 
     col="green")
#The distance from home appears to impact attrition. There is right skew to the data. Indicating those living
#close to their place of employement will attrition out of the company.

hist(True.Attrition$Age,
     main="Age of Employees Impacting Attrition", 
     xlab="Employees Age",
     ylab="Number of Employees",
     border = "blue",
     col="yellow")
#The Age shows a right skew with the older the age the less likely to leave a company.

summary(True.Attrition$Title)
```
#Is there a relationship between age and income, color each point based off of gender? 
# Yes there is a positive relationship betwen age and income. The older individuals tend to make higher monthly income than yougner individuals. 

```{r, echo=TRUE, cache=TRUE, include=TRUE}
library(ggplot2)
par(las=2)

Age2Income<-ggplot(Small.Data, aes(x=Age, y=Income.mos)) +  geom_point(aes(color = Gender)) + stat_smooth(method="lm", color= "black") + xlab("Age of Employee") +  ylab("Monthly Income") + ggtitle("Workforce Income compared to Age") + theme(plot.title = element_text(hjust = 0.5))
Age2Income

```

#What about Life Satisfaction? Is there a discernable relationship there to what?  (Trends and Observations)

```{r, echo=TRUE, cache=TRUE, include=TRUE}
library(ggplot2)
par(las=2)

LifeSat2Home<-ggplot(Data, aes(x=mlg.Home, y=Satisfied)) +  geom_point(aes(color = Gender)) + stat_smooth(method=lm, color= "black") + xlab("Distance from Home") +  ylab("Satisfied with their Job") + ggtitle("Satisfied Life by Distance to Home") + theme(plot.title = element_text(hjust = 0.5)) + coord_flip()
LifeSat2Home


library(plyr)
DSJob <- subset(Data, Title=="Research Scientist")


DS.Satisfied<-ggplot(DSJob, aes(x=Age, y=Satisfied)) +  geom_point(aes(color = Gender)) + stat_smooth(method="lm", color= "black") + xlab("Age of Research Scientist") +  ylab("Satisfied in their Job") + ggtitle("The Age of a Research Scientist Satisfied in their Job") + theme(plot.title = element_text(hjust = 0.5))
DS.Satisfied

DS.Alter<-ggplot(DSJob, aes(x=M.S.D, y=Satisfied)) +  geom_point(aes(color = Gender)) + stat_smooth(method="lm", color= "black") + xlab("Married, Single, Divorced") +  ylab("Satisfied in their Job") + ggtitle("The Age of a Research Scientist Satisfied in their Job") + theme(plot.title = element_text(hjust = 0.5))
DS.Alter
```

```{r, echo=TRUE, cache=TRUE, include=TRUE}

### testing fit lines outside of ggplot
#fit1 <- lm(Age ~ Income.mos, data=Small.Data)
#summary(fit1)
#test <- plot(Age ~ Income.mos, data=Small.Data)
#test + abline(fit1)
```